# Generated by Django 4.2.7 on 2025-05-18 18:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0003_product_sales_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alertrule',
            options={},
        ),
        migrations.AlterModelOptions(
            name='billing',
            options={'ordering': ['-date'], 'verbose_name': 'Billing', 'verbose_name_plural': 'Billings'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='alertrule',
            name='condition',
            field=models.CharField(blank=True, choices=[('lt', 'Less Than'), ('lte', 'Less Than or Equal'), ('gt', 'Greater Than'), ('gte', 'Greater Than or Equal'), ('eq', 'Equal To')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='days_before',
            field=models.IntegerField(blank=True, help_text='Days before expiry to alert', null=True),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.product'),
        ),
        migrations.AddField(
            model_name='alertrule',
            name='threshold',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='alert_type',
            field=models.CharField(choices=[('low_stock', 'Low Stock'), ('expiry', 'Expiry Date'), ('refill', 'Prescription Refill'), ('custom', 'Custom Alert')], max_length=20),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='parameters',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertrule',
            name='recipients',
            field=models.ManyToManyField(related_name='alert_rules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billing',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_billings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='billing',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='billing',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billings', to='pharmacy.patient'),
        ),
        migrations.AlterField(
            model_name='billing',
            name='tax_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('mobile', 'Mobile Payment'), ('bank', 'Bank Transfer'), ('insurance', 'Insurance'), ('check', 'Check')], max_length=20),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['invoice_number'], name='pharmacy_bi_invoice_635a00_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['payment_status'], name='pharmacy_bi_payment_68690f_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['date'], name='pharmacy_bi_date_299259_idx'),
        ),
        migrations.AddIndex(
            model_name='billing',
            index=models.Index(fields=['due_date'], name='pharmacy_bi_due_dat_1cc259_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date'], name='pharmacy_pa_payment_5f6d9f_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_method'], name='pharmacy_pa_payment_d4563a_idx'),
        ),
    ]
