# Generated by Django 4.2.7 on 2025-05-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_alter_alertrule_options_alter_billing_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={},
        ),
        migrations.AlterModelOptions(
            name='saleitem',
            options={},
        ),
        migrations.RemoveField(
            model_name='sale',
            name='tax_amount',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='updated_at',
        ),
    ]
