# Generated by Django 4.2.7 on 2025-05-18 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0008_alter_billing_invoice_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing',
            name='invoice_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
