# Generated by Django 4.2.7 on 2025-05-19 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0012_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
