# Generated by Django 4.2.7 on 2025-06-15 17:10

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0015_heldsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='made_in',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
        migrations.DeleteModel(
            name='HeldSale',
        ),
    ]
