# Generated by Django 4.2.7 on 2025-06-20 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0022_alter_patient_address_alter_patient_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('expiry', 'Product Expiry'), ('low_stock', 'Low Stock'), ('refill', 'Prescription Refill'), ('payment', 'Payment Due'), ('leave_approval', 'Leave Approval'), ('leave_rejection', 'Leave Rejection'), ('leave_request', 'Leave Request'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
