# Generated by Django 4.2.7 on 2025-06-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0023_remove_notification_related_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='related_content_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='related_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
