# Generated by Django 4.2.7 on 2025-06-20 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0024_notification_related_content_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='related_content_type',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='related_object_id',
        ),
    ]
