# Generated by Django 4.2.7 on 2025-07-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0026_alter_stockadjustment_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockadjustment',
            name='reason',
            field=models.CharField(choices=[('expired', 'Expired'), ('damaged', 'Damaged'), ('lost', 'Lost'), ('theft', 'Theft'), ('other', 'Other')], max_length=20),
        ),
    ]
