# Generated by Django 4.2.7 on 2025-07-05 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0030_alter_prescription_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('partially_filled', 'Partially Filled'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
