# Generated by Django 4.2.7 on 2025-05-16 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name_plural': 'Attendance records'},
        ),
        migrations.AlterModelOptions(
            name='payroll',
            options={'verbose_name_plural': 'Payroll records'},
        ),
        migrations.AlterModelOptions(
            name='performancereview',
            options={'ordering': ['-review_date'], 'verbose_name_plural': 'Performance reviews'},
        ),
        migrations.AddField(
            model_name='performancereview',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='performance_score',
            field=models.IntegerField(choices=[(1, 'Poor'), (2, 'Needs Improvement'), (3, 'Meets Expectations'), (4, 'Exceeds Expectations'), (5, 'Outstanding')]),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
