# Generated by Django 4.2.7 on 2025-06-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_attendance_options_alter_payroll_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='payroll',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='payroll',
            name='advance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payroll',
            name='advance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='advance_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='has_advance',
            field=models.BooleanField(default=False),
        ),
    ]
