# Generated by Django 4.2.7 on 2025-06-15 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_leavetype_leaverequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-date_applied'], 'verbose_name': 'Leave Request', 'verbose_name_plural': 'Leave Requests'},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={'verbose_name': 'Leave Type', 'verbose_name_plural': 'Leave Types'},
        ),
    ]
