# Generated by Django 4.2.7 on 2025-06-15 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_leaverequest_options_alter_leavetype_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'ordering': ['-date_applied']},
        ),
        migrations.AlterModelOptions(
            name='leavetype',
            options={},
        ),
    ]
