# Generated by Django 4.2.7 on 2025-06-16 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_leaverequest_options_alter_leavetype_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LeaveRequest',
        ),
        migrations.DeleteModel(
            name='LeaveType',
        ),
    ]
