# Generated by Django 4.2.7 on 2025-06-16 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_leave'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending Payment'), ('paid', 'Paid'), ('not_applicable', 'Not Applicable')], default='pending', max_length=15),
        ),
        migrations.AddField(
            model_name='leave',
            name='payroll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves', to='accounts.payroll'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('paid', 'Paid Leave'), ('unpaid', 'Unpaid Leave'), ('sick', 'Sick Leave'), ('maternity', 'Maternity Leave'), ('paternity', 'Paternity Leave'), ('bereavement', 'Bereavement Leave'), ('compensatory', 'Compensatory Leave')], max_length=20),
        ),
    ]
