# Generated by Django 4.2.7 on 2025-06-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_user_notification_recipient_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='recipient',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_leave_application', 'New Leave Application'), ('leave_status_change', 'Leave Status Change'), ('leave_approved', 'Leave Approved'), ('leave_rejected', 'Leave Rejected'), ('payroll_processed', 'Payroll Processed')], max_length=50),
        ),
        migrations.AlterField(
            model_name='notification',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
