# Generated by Django 4.2.7 on 2025-06-20 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_attendance_options_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={'ordering': ['-month']},
        ),
        migrations.AddField(
            model_name='leave',
            name='medical_certificate',
            field=models.FileField(blank=True, null=True, upload_to='medical_certificates/'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(choices=[('annual', 'Annual Leave (30 days)'), ('sick_1', 'Sick Leave (First 3 months - Full Pay)'), ('sick_2', 'Sick Leave (Next 3 months - Half Pay)'), ('maternity', 'Maternity Leave (4 months)'), ('maternity_miscarriage_9', 'Maternity Leave (90 days - 9th month miscarriage)'), ('maternity_miscarriage_6_8', 'Maternity Leave (60 days - 6-8 month miscarriage)'), ('maternity_miscarriage_3_5', 'Maternity Leave (30 days - 3-5 month miscarriage)'), ('family', 'Family Responsibility Leave (3-7 days)'), ('unpaid', 'Unpaid Leave'), ('compensatory', 'Compensatory Leave')], max_length=30),
        ),
    ]
