# Generated by Django 4.2.7 on 2025-06-20 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_payroll_options_leave_medical_certificate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('expiry', 'Product Expiry'), ('low_stock', 'Low Stock'), ('refill', 'Prescription Refill'), ('payment', 'Payment Due'), ('leave_approval', 'Leave Approval'), ('leave_rejection', 'Leave Rejection'), ('leave_request', 'Leave Request'), ('other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_notifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
