# Generated by Django 4.2.7 on 2025-07-01 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payroll',
            options={},
        ),
    ]
